services:
  server:
    image: hub.biclex.ru/biclex-hub-server:0.3.18
    pull_policy: always
    container_name: biclex-hub-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8123:8123/tcp"
      - "40000-40100:40000-40100/udp"
    volumes:
      - ./data:/data
      - ./logs:/var/log/biclex-hub
      - ./updates:/updates:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "--timeout=3", "http://127.0.0.1:8123/health"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 15s

  turn:
    image: coturn/coturn:4.6.3
    container_name: biclex-hub-turn
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    command:
      - -n
      - --log-file=stdout
      - --fingerprint
      - --listening-ip=0.0.0.0
      - --relay-ip=${TURN_INTERNAL_IP}
      - --lt-cred-mech
      - --realm=turn.biclex.ru
      - --user=${TURN_USERNAME}:${TURN_PASSWORD}
      - --external-ip=${ANNOUNCED_ADDRESS}/${TURN_INTERNAL_IP}
      - --min-port=40200
      - --max-port=40300
      - --no-cli
