services:
  server:
    image: hub.biclex.ru/biclex-hub-server:0.3.17
    pull_policy: always
    container_name: biclex-hub-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8123:8123/tcp"
      - "${RTC_MIN_PORT:-40000}-${RTC_MAX_PORT:-40100}:${RTC_MIN_PORT:-40000}-${RTC_MAX_PORT:-40100}/udp"
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "--timeout=3", "http://127.0.0.1:8123/health"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 15s

  turn:
    image: coturn/coturn:4.6.3
    container_name: biclex-hub-turn
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    command:
      - -n
      - --log-file=stdout
      - --fingerprint
      - --listening-ip=0.0.0.0
      - --lt-cred-mech
      - --realm=BicLex
      - --user=${TURN_USERNAME}:${TURN_PASSWORD}
      - --external-ip=${ANNOUNCED_ADDRESS}
      - --min-port=40200
      - --max-port=40300
      - --no-cli
